server:
  port: 8080

spring:
  application:
    name: observability

management:
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"

logging.pattern.level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"