version: '4.19.0'

networks:
  aw-network:
    driver: bridge

volumes:
  app_data:
  zipkin_data:
  prometheus_data:
  grafana_data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - aw-network
    ports:
      - "8080:8080"
    volumes:
      - ./application.yml:/app/application.yml
      - app_data:/app
  zipkin:
    image: openzipkin/zipkin:latest
    networks:
      - aw-network
    ports:
      - "9411:9411"
    volumes:
      - zipkin_data:/zipkin
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    networks:
      - aw-network
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    networks:
      - aw-network
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/grafana